# Social media use during Covid-19 pandemic

## 1 Introduction

In the present notebook, we will use a parametric and a non-parametric test to assess the difference in the amounts of time spent on social media between groups of students who used either a computer or a smartphone for their coursework in the Covid-19 pandemic.

## 2 Executive summary

[SUMMARY HERE]

## 3 Report

### 3.1 Report introduction

This is an interesting cross-section of data from a survey of 1078 respondents. We have individuals' IDs, ages and the region of residence. We further have information on on the device used to access online classes and on the prefered social media platform and stress activity. We further have individuals' time spent on classes, self-study, fitness, sleep, social media and TV. Last but not least, we have responses on the daily number of meals, change in weight, presence of health issues and whether the respondents feel connected to their family and friends.

The present dataset comes from DataCamp's [A/B Testing in R](https://app.datacamp.com/learn/courses/ab-testing-in-r?cf-exp=comm--ai-native-cdp-layout%3Aon) course.

### 3.2 Deliverables

[DELIVERABLES HERE]

### 3.3 Methods

[METHODS HERE]

### 3.4 Discussion

[DISCUSSION HERE]

### 3.5 Recommendations

[RECOMMENDATIONS HERE]

In [3]:
# Libraries
library(tidyverse)
library(readxl)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Workings

### Helpers

In [10]:
# Custom functionality and libraries
#devtools::install_github("tros01/google_advanced_data_analytics", subdir = "custom_libraries/utils")
library(gada.utils)

#### Graphing setup

In [1]:
# Set up Jupyter graph display
options(
  repr.plot.width = 10,
  repr.plot.height = 6,
  repr.plot.res = 150
)

### Load and verify the data

In [44]:
# Load up the data into a df
df <- read_csv(
    file.path(r"(data/covid.csv)"),
    col_names = TRUE,
    col_types = NULL,
    show_col_types = FALSE
)

In [9]:
# Dimension check
df |> dim()

[1] 1078   21

The dataset appears to be complete.

In [45]:
# Format column names
df <- df |> janitor::clean_names()

In [7]:
# Display a sample
df |> sample_n(5)

  x_1 x   id   region_of_residence age_of_subject time_spent_on_online_class
1 940 940 1033 Outside Delhi-NCR   25             0
2  40  40 R44  Delhi-NCR           21             5
3 984 984 1081 Delhi-NCR           15             3
4  35  35 R38  Outside Delhi-NCR   20             4
5 582 582 R657 Delhi-NCR           19             4
  rating_of_online_class_experience medium_for_online_class
1 Very poor                         Smartphone
2 Very poor                         Laptop/Desktop
3 Average                           Smartphone
4 Average                           Laptop/Desktop
5 Very poor                         Smartphone
  time_spent_on_self_study time_spent_on_fitness ⋯ time_spent_on_social_media
1 2                        0.0                   ⋯ 5
2 3                        1.0                   ⋯ 1
3 4                        0.5                   ⋯ 1
4 2                        0.0                   ⋯ 2
5 5                        0.0                   ⋯ 2
  prefered_social_media_platform time_spent_on_tv number_of_meals_per_day
1 Facebook                       0                3
2 Instagram                      0                2
3 Instagram                      1.5              4
4 Instagram                      0                3
5 Whatsapp                       0                3
  change_in_your_weight health_issue_during_lockdown stress_busters
1 Remain Constant       NO                           Listening to music
2 Increased             NO                           Listening to music
3 Increased             NO                           Listening to music
4 Increased             NO                           Sleep
5 Increased             NO                           Reading books
  time_utilized
1 NO
2 NO
3 YES
4 NO
5 YES
  do_you_find_yourself_more_connected_with_your_family_close_friends_relatives
1 YES
2 NO
3 YES
4 YES
5 YES
  what_you_miss_the_most
1 Roaming around freely
2 Eating outside
3 Eating outside
4 Eating outside
5 School/college

In [11]:
# df structure
df |> str()

spc_tbl_ [1,078 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ x_1                                                                         : num [1:1078] 2 4 6 7 11 12 13 14 15 16 ...
 $ x                                                                           : num [1:1078] 2 4 6 7 11 12 13 14 15 16 ...
 $ id                                                                          : chr [1:1078] "R2" "R4" "R6" "R7" ...
 $ region_of_residence                                                         : chr [1:1078] "Delhi-NCR" "Delhi-NCR" "Delhi-NCR" "Delhi-NCR" ...
 $ age_of_subject                                                              : num [1:1078] 21 20 21 19 21 21 22 20 22 20 ...
 $ time_spent_on_online_class                                                  : num [1:1078] 0 3 0 2 1 3 1 5 3 0 ...
 $ rating_of_online_class_experience                                           : chr [1:1078] "Excellent" "Very poor" "Very poor" "Very poor" ...
 $ medium_for_online_class                                                     : chr [1:1078] "Smartphone" "Smartphone" "Smartphone" "Smartphone" ...
 $ time_spent_on_self_study                                                    : num [1:1078] 0 2 6 2 0 0 2 1 3 0 ...
 $ time_spent_on_fitness                                                       : num [1:1078] 2 1 0 1 1 0 0 0 1 0 ...
 $ time_spent_on_sleep                                                         : num [1:1078] 10 6 5 5 7 8 7 8 6 8 ...
 $ time_spent_on_social_media                                                  : num [1:1078] 3 5 1 4 3 3 0 3 2 2 ...
 $ prefered_social_media_platform                                              : chr [1:1078] "Youtube" "Instagram" "Youtube" "Instagram" ...
 $ time_spent_on_tv                                                            : chr [1:1078] "0" "0" "0" "0" ...
 $ number_of_meals_per_day                                                     : num [1:1078] 3 3 1 3 2 3 2 3 3 3 ...
 $ change_in_your_weight                                                       : chr [1:1078] "Decreased" "Decreased" "Decreased" "Increased" ...
 $ health_issue_during_lockdown                                                : chr [1:1078] "NO" "NO" "YES" "NO" ...
 $ stress_busters                                                              : chr [1:1078] "Scrolling through social media" "Watching web series" "Coding and studying for exams" "Watching web series" ...
 $ time_utilized                                                               : chr [1:1078] "YES" "NO" "NO" "NO" ...
 $ do_you_find_yourself_more_connected_with_your_family_close_friends_relatives: chr [1:1078] "NO" "NO" "YES" "YES" ...
 $ what_you_miss_the_most                                                      : chr [1:1078] "Roaming around freely" "Friends , relatives" "School/college" "Friends , relatives" ...
 - attr(*, "spec")=
  .. cols(
  ..   X.1 = col_double(),
  ..   X = col_double(),
  ..   ID = col_character(),
  ..   Region.of.residence = col_character(),
  ..   Age.of.Subject = col_double(),
  ..   Time.spent.on.Online.Class = col_double(),
  ..   Rating.of.Online.Class.experience = col_character(),
  ..   Medium.for.online.class = col_character(),
  ..   Time.spent.on.self.study = col_double(),
  ..   Time.spent.on.fitness = col_double(),
  ..   Time.spent.on.sleep = col_double(),
  ..   Time.spent.on.social.media = col_double(),
  ..   Prefered.social.media.platform = col_character(),
  ..   Time.spent.on.TV = col_character(),
  ..   Number.of.meals.per.day = col_double(),
  ..   Change.in.your.weight = col_character(),
  ..   Health.issue.during.lockdown = col_character(),
  ..   Stress.busters = col_character(),
  ..   Time.utilized = col_character(),
  ..   Do.you.find.yourself.more.connected.with.your.family..close.friends...relatives... = col_character(),
  ..   What.you.miss.the.most = col_character()
  .. )
 - attr(*, "problems")=<externalptr>

- region of residence, class rating, medium, change in weight and binary variables are factors
- prefered social media platform is potentially a factor
- time spent on TV is a numeric variable

In [ ]:
# Unordered factor variables
factor_vars <- c(
    "region_of_residence",    
    "medium_for_online_class",
    "prefered_social_media_platform",
    "change_in_your_weight",
    "health_issue_during_lockdown",
    "time_utilized",
    "do_you_find_yourself_more_connected_with_your_family_close_friends_relatives"
)

In [47]:
# Unordered factors
for (var in factor_vars) {
    levels <- df |>
        select(all_of(var)) |>
        drop_na() |> 
        pull() |>
        str_squish() |> 
        str_to_lower() |>
        str_replace_all("[ -/]", "_") |>
        unique()

    df <- df |>
        mutate(
            !!sym(var) := str_replace_all(str_to_lower(str_squish(!!sym(var))), "[ -/]", "_"),
            !!sym(var) := factor(!!sym(var), levels = levels, ordered = FALSE)
        )
}

In [48]:
# Ordered factors and numeric vars
levels <- df |>
        select(rating_of_online_class_experience) |>
        drop_na() |> 
        pull() |>
        str_squish() |> 
        str_to_lower() |>
        str_replace_all("[ -/]", "_") |>
        unique()

ordered_levels <- levels[c(2, 5, 3, 4, 1)]

df <- df |>
    mutate(
        rating_of_online_class_experience = factor(rating_of_online_class_experience, levels = ordered_levels, ordered = TRUE),
        time_spent_on_tv = as.numeric(time_spent_on_tv)
    )

Warning message:
"There was 1 warning in `mutate()`.
ℹ In argument: `time_spent_on_tv = as.numeric(time_spent_on_tv)`.
Caused by warning:
! NAs introduced by coercion"

In [50]:
# Sample the df
df |> sample_n(5)

  x_1 x   id   region_of_residence age_of_subject time_spent_on_online_class
1 285 285 R315 delhi_ncr           19             1
2 154 154 R165 delhi_ncr           22             1
3 995 995 1093 delhi_ncr           17             6
4 694 694 R774 delhi_ncr           40             6
5 610 610 R686 delhi_ncr           21             3
  rating_of_online_class_experience medium_for_online_class
1 NA                                laptop_desktop
2 NA                                smartphone
3 NA                                smartphone
4 NA                                laptop_desktop
5 NA                                laptop_desktop
  time_spent_on_self_study time_spent_on_fitness ⋯ time_spent_on_social_media
1 3                        2                     ⋯ 1
2 4                        1                     ⋯ 2
3 1                        0                     ⋯ 1
4 3                        0                     ⋯ 2
5 4                        1                     ⋯ 1
  prefered_social_media_platform time_spent_on_tv number_of_meals_per_day
1 instagram                      2                2
2 linkedin                       0                2
3 reddit                         0                2
4 whatsapp                       2                3
5 youtube                        2                4
  change_in_your_weight health_issue_during_lockdown
1 remain_constant       yes
2 increased             yes
3 remain_constant       no
4 remain_constant       no
5 decreased             no
  stress_busters               time_utilized
1 Online gaming                no
2 Watching web series          no
3 Online gaming                no
4 No able to reduce the stress no
5 Meditation                   no
  do_you_find_yourself_more_connected_with_your_family_close_friends_relatives
1 no
2 no
3 no
4 yes
5 yes
  what_you_miss_the_most
1 School/college
2 Roaming around freely
3 Metro
4 Travelling
5 Friends , relatives

#### Investigate NAs, negatives, duplicates